name: Force Redeploy to Railway

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  RAILWAY_PROJECT_ID: 3a915e17-0b3c-4900-adb4-5aab85f39fdd
  RAILWAY_SERVICE_NAME: frontend

jobs:
  force-redeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Link to Railway project
        run: |
          railway link -p ${{ env.RAILWAY_PROJECT_ID }} -s ${{ env.RAILWAY_SERVICE_NAME }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Force redeploy to Railway
        run: |
          echo "Force redeploying to Railway..."
          railway redeploy --service ${{ env.RAILWAY_SERVICE_NAME }} -y
          echo "Redeploy triggered successfully!"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Wait for deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          echo "Deployment should be ready!"

      - name: Get deployment status
        run: |
          railway status --service ${{ env.RAILWAY_SERVICE_NAME }}
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        continue-on-error: true 
